source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-flash'
gem 'sinatra-contrib'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'thin'
gem 'warden'
gem 'bcrypt-ruby'
gem 'slim'
gem 'sass'
gem 'rest-client'
gem 'pry'